Repository THE-SOPT-Joint-Seminar-ZEPETO/ZEPETO-iOS, pull requests merged in 2022-05, with the labels that each got.

#7 ✨ [FEAT] Create Edit View UI 구성
  ZEPETO-iOS/ZEPETO-iOS.xcodeproj/project.pbxproj
  ZEPETO-iOS/ZEPETO-iOS/Global/Struct/Identifiers.swift
  ZEPETO-iOS/ZEPETO-iOS/Screen/CreateEdit/SB/CreateEditSB.storyboard
  ZEPETO-iOS/ZEPETO-iOS/Screen/CreateEdit/VC/CreateEditVC.swift
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icAaLine.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icAaLine.imageset/icAaLine.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icAaLine.imageset/icAaLine@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icAaLine.imageset/icAaLine@3x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icDownloadLine.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icDownloadLine.imageset/icDownloadLine.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icDownloadLine.imageset/icDownloadLine@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icDownloadLine.imageset/icDownloadLine@3x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icFilterLilne.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icFilterLilne.imageset/icFilterLilne.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icFilterLilne.imageset/icFilterLilne@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icFilterLilne.imageset/icFilterLilne@3x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icSmileLine.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icSmileLine.imageset/icSmileLine.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icSmileLine.imageset/icSmileLine@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icSmileLine.imageset/icSmileLine@3x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icTwosquareLilne.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icTwosquareLilne.imageset/icTwosquareLilne.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icTwosquareLilne.imageset/icTwosquareLilne@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icTwosquareLilne.imageset/icTwosquareLilne@3x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icUserLinePlus.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icUserLinePlus.imageset/icUserLinePlus.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icUserLinePlus.imageset/icUserLinePlus@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icUserLinePlus.imageset/icUserLinePlus@3x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icXLine.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icXLine.imageset/icXLine.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icXLine.imageset/icXLine@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icXLine.imageset/icXLine@3x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/image.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/image.imageset/image.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/image.imageset/image@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/image.imageset/image@3x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/iosButtonFloating.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/iosButtonFloating.imageset/iosButtonFloating.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/iosButtonFloating.imageset/iosButtonFloating@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/iosButtonFloating.imageset/iosButtonFloating@3x.png
Labels: 📱 View, 🍎 Feature, 💛 주현 💛

#8 ✨ [FEAT] Create Upload View UI 구성
  ZEPETO-iOS/ZEPETO-iOS.xcodeproj/project.pbxproj
  ZEPETO-iOS/ZEPETO-iOS.xcodeproj/xcshareddata/xcschemes/ZEPETO-iOS.xcscheme
  ZEPETO-iOS/ZEPETO-iOS/Screen/CreateUpload/SB/CreateUploadSB.storyboard
  ZEPETO-iOS/ZEPETO-iOS/Screen/CreateUpload/VC/CreateUploadVC.swift
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icArrowLineRight.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icArrowLineRight.imageset/icArrowLineRight.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icArrowLineRight.imageset/icArrowLineRight@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icArrowLineRight.imageset/icArrowLineRight@3x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icChatFill.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icChatFill.imageset/icChatFill.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icChatFill.imageset/icChatFill@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icChatFill.imageset/icChatFill@3x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icHashLilne.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icHashLilne.imageset/ic_hash_lilne.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icHashLilne.imageset/ic_hash_lilne@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icHashLilne.imageset/ic_hash_lilne@3x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icIdcardsFill.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icIdcardsFill.imageset/icIdcardsFill.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icIdcardsFill.imageset/icIdcardsFill@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icIdcardsFill.imageset/icIdcardsFill@3x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icLeftbutton.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icLeftbutton.imageset/icLeftbutton.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icLeftbutton.imageset/icLeftbutton@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icLeftbutton.imageset/icLeftbutton@3x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icPlanetFill.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icPlanetFill.imageset/icPlanetFill.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icPlanetFill.imageset/icPlanetFill@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icPlanetFill.imageset/icPlanetFill@3x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icUserFill.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icUserFill.imageset/icUserFill.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icUserFill.imageset/icUserFill@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/icUserFill.imageset/icUserFill@3x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/skyBackground.imageset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/skyBackground.imageset/skyBackground@1x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Assets.xcassets/skyBackground.imageset/skyBackground@2x.png
  ZEPETO-iOS/ZEPETO-iOS/Support/Colorsets.xcassets/gay800.colorset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Colorsets.xcassets/gray150.colorset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Colorsets.xcassets/gray600.colorset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Colorsets.xcassets/gray800.colorset/Contents.json
  ZEPETO-iOS/ZEPETO-iOS/Support/Info.plist
  ZEPETO-iOS/ZEPETO-iOS/Support/SceneDelegate.swift
Labels: 📱 View, 🍎 Feature, 🙋🏻‍♀️ Question, 💙 정연 💙

#10 ✨ [FEAT] CreateMain -> CreateEdit 이미지 전달
  ZEPETO-iOS/ZEPETO-iOS/Screen/CreateEdit/SB/CreateEditSB.storyboard
  ZEPETO-iOS/ZEPETO-iOS/Screen/CreateEdit/VC/CreateEditVC.swift
  ZEPETO-iOS/ZEPETO-iOS/Screen/CreateMain/VC/CreateMainVC.swift
Labels: 📱 View, 🍎 Feature, 💛 주현 💛

#16 ✨ [FEAT] 화면전환 플로우 연결
  ZEPETO-iOS/ZEPETO-iOS/Screen/CreateEdit/SB/CreateEditSB.storyboard
  ZEPETO-iOS/ZEPETO-iOS/Screen/CreateEdit/VC/CreateEditVC.swift
  ZEPETO-iOS/ZEPETO-iOS/Screen/CreateMain/VC/CreateMainVC.swift
  ZEPETO-iOS/ZEPETO-iOS/Screen/CreateUpload/SB/CreateUploadSB.storyboard
  ZEPETO-iOS/ZEPETO-iOS/Screen/CreateUpload/VC/CreateUploadVC.swift
  ZEPETO-iOS/ZEPETO-iOS/Screen/Feed/SB/FeedSB.storyboard
  ZEPETO-iOS/ZEPETO-iOS/Screen/Feed/VC/FeedVC.swift
  ZEPETO-iOS/ZEPETO-iOS/Screen/TabBar/VC/ZepetoTBC.swift
Labels: 📱 View, 🍎 Feature, 💜 은주 💜
